// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGGisSPCO1ZGTiH2EGhuJ9OL6VJZ_TihE',
    appId: '1:1008162616142:web:5b69db77814a37ab5a241f',
    messagingSenderId: '1008162616142',
    projectId: 'bees-8e71d',
    authDomain: 'bees-8e71d.firebaseapp.com',
    storageBucket: 'bees-8e71d.appspot.com',
    measurementId: 'G-VREL1YZ8YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBULW5bX9pa3WB7aUi4eXxhuRJhsUrpkhE',
    appId: '1:1008162616142:android:7381c42293f1bde45a241f',
    messagingSenderId: '1008162616142',
    projectId: 'bees-8e71d',
    storageBucket: 'bees-8e71d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtJQlvAmL3LQme0qhRVZoqAPvWTELIDVU',
    appId: '1:1008162616142:ios:88dc9c2f225fe8ac5a241f',
    messagingSenderId: '1008162616142',
    projectId: 'bees-8e71d',
    storageBucket: 'bees-8e71d.appspot.com',
    iosBundleId: 'com.example.bee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtJQlvAmL3LQme0qhRVZoqAPvWTELIDVU',
    appId: '1:1008162616142:ios:ca635b9ea2ea92f85a241f',
    messagingSenderId: '1008162616142',
    projectId: 'bees-8e71d',
    storageBucket: 'bees-8e71d.appspot.com',
    iosBundleId: 'com.example.bee.RunnerTests',
  );
}
